FROM node:10-alpine
COPY package.json /
WORKDIR /
RUN apk update && apk add python openjdk7 make g++
ENV JAVA_HOME=/usr/lib/jvm/java-1.7-openjdk
ENV PATH=$PATH:/usr/lib/jvm/java-1.7-openjdk/bin
RUN npm install
CMD npm run build
#EXPOSE 8081
